# Generated by Django 4.2.30 on 2026-08-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScreeningResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("resume_filename", models.CharField(blank=True, max_length=255)),
                ("resume_text", models.TextField()),
                ("jd_text", models.TextField()),
                ("match_score", models.FloatField()),
                ("sbert_score", models.FloatField(blank=True, null=True)),
                ("tfidf_score", models.FloatField()),
                ("method", models.CharField(max_length=20)),
                ("matched_skills", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("resume_skills", models.JSONField(default=list)),
                ("jd_skills", models.JSONField(default=list)),
                ("recommendation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
