# Generated by Django 4.2.30 on 2026-08-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("screening_id", models.IntegerField(blank=True, null=True)),
                ("n_questions", models.IntegerField(default=5)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("strengths", models.JSONField(default=list)),
                ("gaps", models.JSONField(default=list)),
                ("overall_verdict", models.TextField(blank=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.IntegerField()),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("score", models.IntegerField(blank=True, null=True)),
                ("justification", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="interview.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["question_number"],
            },
        ),
    ]
