# Generated by Django 4.2.30 on 2026-08-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewanswer",
            name="correct_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="question_type",
            field=models.CharField(default="text", max_length=10),
        ),
    ]
